name: Sync Repos

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour

  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        include:
          - repo_to_update: '${{ github.repository_owner }}/winget-pkgs'
            remote_repo: 'https://github.com/microsoft/winget-pkgs.git'
            remote_ref: 'master'
            ref_to_update: 'master'
            force_push: true
          - repo_to_update: '${{ github.repository_owner }}/bsqmods'
            remote_repo: 'https://github.com/QuestPackageManager/bsqmods'
            remote_ref: 'main'
            ref_to_update: 'main'
            force_push: false

    steps:
      - name: Checkout remote repository
        run: |
          git clone --branch "${{ matrix.remote_ref }}" "${{ matrix.remote_repo }}" .
          
      - name: Add repository to be updated
        run: |
          git remote add update "https://${{ github.repository_owner }}:${{ secrets.METRICS_TOKEN }}@github.com/${{ matrix.repo_to_update }}.git"
          git fetch update

      - name: Push to repository to be updated
        run: |
          if [ "${{ matrix.force_push }}" == "true" ]; then
            git push update "${{ matrix.remote_ref }}:${{ matrix.ref_to_update }}" --force
          else
            git push update "${{ matrix.remote_ref }}:${{ matrix.ref_to_update }}"
          fi

  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Ammend commit and force-push the current repo
        continue-on-error: true
        run: |
          mkdir -p "${{ github.repository }}"
          cd "${{ github.repository }}"
          git clone "https://${{ github.repository_owner }}:${{ secrets.METRICS_TOKEN }}@github.com/${{ github.repository }}.git" .
          git config user.name "$(git log -1 --pretty=format:"%an")"
          git config user.email "$(git log -1 --pretty=format:"%ae")"
          git commit --amend --no-edit
          git push --force
