name: Update Amiibo Data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # Runs every hour

jobs:
  dispatch:
    uses: ./.github/workflows/dispatch-workflow.yml
    with:
      repository: DanTheMan827/AmiiboData
      workflow: update-data.yml
